### ISSUE TITLE
Why not using MongoDB Dart driver?

### ISSUE THREAD

**Issue by aytunch** [mmcc007/grpc_series_flutter#6]
I have seen that there are some limitations for MongoDB dart package like the lack of watch support. But for geolocation is there any more lack of support? Do you recomend Java over Dart for MongoDB? Where can we serve this server as a cloud solution? Thanks for sharing this experience. I hope you can write a medium article one day for this.

One more question. Have you tried Postgres instead of MongoDB? They have dart adapters. I want to know if it is a better option than MongoDB in terms of geolocation, gprc compliance, performance, etc.

**Comment by mmcc007** [comment]
I haven't used MongoDB or the MongoDB dart package much, so not sure what you have in mind for geolocation in context of MongoDB or if I can provide insight. 

Based on what I know, I would recommend Java over Dart for MongoDB. There seems to be no intention of supporting Dart on the server, but this may change in the future. Serving a gRPC Java server in the cloud should be a well-understood procedure, as it is widely used (though I have not done it myself). See [https://github.com/yidongnan/grpc-spring-boot-starter](https://github.com/yidongnan/grpc-spring-boot-starter) as a starting point.

On first look, the [postgres package](https://pub.dev/packages/postgres) allows you to run SQL but does not seem to implement any of Postgres's GIS features. So again, would be looking at using some other language on the server side with a fully implemented Postgres driver.

Good luck!

**Comment by aytunch** [comment]
Thank you very much for your insights.
